import Head from "next/head";

import Componente from "@/components/Componente"
// import ComponenteHTML from "@/components/ComponenteHTML"
// import ComponenteCSS from "@/components/ComponenteCSS"
// import ComponenteJavaScript from "@/components/ComponenteJavaScript"
// import ComponenteNode from "@/components/ComponenteNode"
// import ComponenteExpress from "@/components/ComponenteExpress"
import data from "@/data/data";
import languages from "@/data/languages";

export default function Home() {

  // const title='titolo';
  // const description='descrizione';


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       {/* <Componente title={title} description={description} /> */}
       
        {languages.map((lang) => (
          <Componente
            key={lang.id}
            title={lang.title}
            description={lang.description}
          />
        ))}

      {/* <ComponenteHTML />
      <ComponenteCSS />
      <ComponenteJavaScript />
      <ComponenteNode />
      <ComponenteExpress /> */}
    </>
  );
}
